[build]
  base = "./"
  command = "hugo"
  publish = "./public/"

  [build.environment]
    HUGO_ENV = "production"
    HUGO_VERSION = "0.40"

[context.deploy-preview]
  command = "hugo  --buildDrafts --buildFuture"
