[build]
  base = "./"
  command = "hugo"
  publish = "./public/"

  [build.environment]
    HUGO_ENV = "production"
    HUGO_VERSION = "0.40.2"

[context.deploy-preview]
  command = "hugo --baseURL $DEPLOY_PRIME_URL --buildDrafts --buildFuture"
