version: 2

aliases:
  - &defaults
    docker:
      - image: circleci/node:10.18.1
    environment:
      NODE_ENV: development
    working_directory: ~/projects/ykzts.blog/

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-dependencies-{{ checksum "yarn.lock" }}
            - v1-node-dependencies-
      - run: yarn install --frozen-lockfile
      - save_cache:
          key: v1-node-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/
      - run: yarn lint
      - persist_to_workspace:
          paths:
            - ./*
          root: .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run: yarn build

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
